### ISSUE TITLE
rr:template in rr:subjectMap should be optional

### ISSUE THREAD

**Issue by bblfish** [kg-construct/rml-questions#20]
`rr:template` is not optional in the `rr:subjectMap` as defined by https://rml.io/specs/rml/  .
The rmlmapper-java implementation at least fails to run when `rr:subjectMap` is missing.

Given a basic CSV table this won't compile with `rmlmapper-java`

```
<#allDataMap>
    rml:logicalSource [
      rml:referenceFormulation ql:CSV ;
      rml:source  "all_data.csv"
    ] .
<#allDataMap> a rr:TriplesMap;
    rr:subjectMap [
        rr:class sosa:Observation;
    ] .
```   
Some example data: 
```csv
 ,timestamp,data_source,index,modality,count,locationrange,speed,measurement_type,refRoadSegment
480,2021-09-05 22:00:00+00:00,cropland,schoolstraat,,3553.3899,"POLYGON ((4.472119613057031 51.02073678178503, 4.479745501704901 51.02015981281664, 4.481188984378538 51.01915526700179, 4.481395603399528 51.01491440180675, 4.482127375233162 51.0126494593307, 4.478332541440828 51.00987874451822, 4.471306586318185 51.00931972134209, 4.469785136941451 51.01107192511326, 4.461581573935097 51.01126112376583, 4.460354540525603 51.01217411043578, 4.46032051949892 51.01700860830363, 4.468571374013287 51.01807235138044, 4.472119613057031 51.02073678178503))",,,
481,2021-09-05 22:15:00+00:00,cropland,schoolstraat,,2760.2395,"POLYGON ((4.472119613057031 51.02073678178503, 4.479745501704901 51.02015981281664, 4.481188984378538 51.01915526700179, 4.481395603399528 51.01491440180675, 4.482127375233162 51.0126494593307, 4.478332541440828 51.00987874451822, 4.471306586318185 51.00931972134209, 4.469785136941451 51.01107192511326, 4.461581573935097 51.01126112376583, 4.460354540525603 51.01217411043578, 4.46032051949892 51.01700860830363, 4.468571374013287 51.01807235138044, 4.472119613057031 51.02073678178503))",,,
```

 I posted a question on the `rmlmapper-java` site and was pointed here https://github.com/RMLio/rmlmapper-java/issues/182

In a mapping process the most important things to map are in order datatypes, then the relations then the types, then the instances. This is easy to see with CSV. Relations should be generated automatically as relative URLs if specified.

This is important for educational and pragmatic reasons. 
1. educational: we should argue that all CVS or SQL DB data is RDF already: it is just that relative URLs are being used for the relations, and no documentation is associated to that relation. Adding a URL there allows one to 
   * specify that columns in two different data sets are speaking about the same thing
   * put documentation (html and RDF) at that URL location
2. Knowing where the data is going to get published and so what full URLs for the instance data should be used, is often a decision made much later in the mapping process.  A Blank node simplifies the mapping process there, and allows them to be introduced when the need is felt.  Often a relative URL template would be the best. 

The fact that the Turtle mapping files can be split is already a big advantage in allowing mappings tasks to be split across departments or time. The main otology mapping may be the job of the ontology engineer, and the data mapping of the web data engineer.

So to make it easier for larger processes to split the mapping processes between different departments and over time it would be best if the template were optional.

**Comment by dachafra** [comment]
You can generate automatically blank nodes for resources. See for example (https://rml.io/test-cases/#rmltc0012d-csv). I think RMLMapper allows to not use `rr:template` if `rr:termType rr:BlankNode` is provided and it generates an auto-generated identifier for the blank nodes (but try bc I'm not sure). We are also working towards this issue here: https://github.com/kg-construct/rml-fno-spec/issues/24 and we will be more flexible during the mapping process.

The rest of the discussion, IMO, is more a philosophical discussion on how the users and different use-cases are adapting to the mapping process.

**Comment by bblfish** [comment]
yep, that works. 

Thanks for the help. I am just getting to work my way around the specs. Hope some of the comments are useful :-)

**Comment by dachafra** [comment]
thanks!
