### ISSUE TITLE
ql ontology missing

### ISSUE THREAD

**Issue by bblfish** [kg-construct/rml-questions#21]
I can't get the `ql` ontology, which is defined/used in the https://rml.io/specs/rml/ spec 

```sh
> curl -i http://semweb.mmlab.be/ns/ql
HTTP/1.1 404 Not Found
Date: Mon, 11 Jul 2022 12:30:55 GMT
Server: Apache/2.4.41 (Ubuntu)
X-Powered-By: Express
Content-Type: text/html; charset=utf-8
Content-Length: 12
ETag: "703595115"
Vary: Accept-Encoding

Nothing here%
```
I was pointed here from https://github.com/RMLio/rmlmapper-java/issues/181

**Comment by andimou** [comment]
I do not think that the ql was ever defined.

**Comment by dachafra** [comment]
I think this is an issue that can be moved to the core spec and addressed in the new iteration of the RML ontology, what do you think? @anaigmo

**Comment by DylanVanAssche** [comment]
The new RML ontology addresses this, see RML IO.
