### ISSUE TITLE
CSV columns with empty names ""

### ISSUE THREAD

**Issue by bblfish** [kg-construct/rml-questions#22]
I have an example CSV table where the first column is an empty string.  
There seems to be no way to capture the content of that column in rmlmapper-java, as
reported in issue 179

https://github.com/RMLio/rmlmapper-java/issues/179

which spec requires the column not have an empty name? It seems an empty string is a string like any other and it should also be allowed (at least once!)

**Comment by dachafra** [comment]
@bblfish can you open this issue as a discussion better? thanks!
https://github.com/kg-construct/rml-questions/discussions

**Comment by bblfish** [comment]
I opened a question here https://github.com/kg-construct/rml-questions/discussions/25
