### ISSUE TITLE
Call to slugify for subjectMap? 

### ISSUE THREAD

**Issue by GenEars** [kg-construct/rml-questions#29]
Dear RML team/users,

With the [rmlmapper-java](https://github.com/RMLio/rmlmapper-java) tool, I wish I could generate subjects with a `rr:subjectMap [ rr:template "http://example.org/doc/{id}" ; ] ;` structure where `{id}` would be slugified with [rmlmapper/default-functions#slugify](https://rml.io/docs/rmlmapper/default-functions/#slugify).

However it seems that functions results cannot be passed to a `rr:template` structure.
There on, I thought of using the `concat` default function (not handy for complex URIs !) or generate complex slugified URIs thorugh an adhoc `fno:Function`.

... do you have any piece of advice about this?

**Comment by dachafra** [comment]
@GenEars If this is a problem with the engine please, open an issue in its repo. If it is a problem on how to create the mapping, please open a discussion [here](https://github.com/kg-construct/rml-questions/discussions)

**Comment by GenEars** [comment]
My question looks similar to https://github.com/kg-construct/rml-questions/discussions/15
Thanks for the *discussion* link.
