### ISSUE TITLE
Runtime generated UUID in subjectMap

### ISSUE THREAD

**Issue by MaFi2000** [kg-construct/rml-questions#49]
### Discussed in https://github.com/kg-construct/rml-questions/discussions/48

<div type='discussions-op-text'>

<sup>Originally posted by **MaFi2000** August 23, 2023</sup>
hello,
I want to generate a uuid based IRI as subject and to add my predicateObjects to it.
Problem is that every triples has different subjects even if those are the same instances.

Here is my mapping:

`  
<#testuuid> 

    rml:logicalSource <#LogicalSource2> ;
    rr:subjectMap [
        fnml:execution <#GetUUID> ;
        rr:termType rr:BlankNode;
    ];
    rr:predicateObjectMap [
        rr:predicate ex:rmsidentifier;                     
        rr:objectMap [
            rml:reference "first_name"; 
        ];
    ];
    rr:predicateObjectMap [
        rr:predicate ex:last_name;                     
        rr:objectMap [
            rml:reference "last_name"; 
        ];
    ].
<#GetUUID>

    fnml:function <https://github.com/morph-kgc/morph-kgc/function/built-in.ttl#uuid> ; 
.

`
    

That is my output

`_:b4d4e7a0-5746-4be4-ba86-67b6b4c15a21 <http://www.example.co.uk/last_name> "Turcotte" .
_:7346acfd-908e-42f6-aa42-7b63605cfe80 <http://www.example.co.uk/last_name> "Parisian" .
_:32dadd9e-24a1-4a76-8213-8a180add4171 <http://www.example.co.uk/last_name> "Daugherty" .
_:fb6cd890-8ae4-4412-beb9-1efb1eed4233 <http://www.example.co.uk/rmsidentifier> "Edwin" .
_:f1139dc5-ce6b-4645-a0cf-264f3820ef8f <http://www.example.co.uk/rmsidentifier> "Kelley" .
_:bcea650f-3547-448d-a31e-eb9847c1bc3e <http://www.example.co.uk/rmsidentifier> "Jewel" .`

 
That is the output I want to get/expect to get:
`_:bcea650f-3547-448d-a31e-eb9847c1bc3e <http://www.example.co.uk/last_name> "Turcotte" .
_:f1139dc5-ce6b-4645-a0cf-264f3820ef8f <http://www.example.co.uk/last_name> "Parisian" .
_:fb6cd890-8ae4-4412-beb9-1efb1eed4233 <http://www.example.co.uk/last_name> "Daugherty" .
_:fb6cd890-8ae4-4412-beb9-1efb1eed4233 <http://www.example.co.uk/rmsidentifier> "Edwin" .
_:f1139dc5-ce6b-4645-a0cf-264f3820ef8f <http://www.example.co.uk/rmsidentifier> "Kelley" .
_:bcea650f-3547-448d-a31e-eb9847c1bc3e <http://www.example.co.uk/rmsidentifier> "Jewel" .`</div>

**Comment by dachafra** [comment]
Hi, I think you are using Morph-KGC right? As I told you in the discussion, this seems a problem of the engine, so I would suggest to open an issue in its repository, not here that are questions more related with the mapping language
